### ISSUE TITLE
Ecto.Model is deprecated

### ISSUE THREAD

**Issue by developerworks** [pma/riak_ecto#3]
Warning: this module is currently deprecated. Instead use Ecto.Schema and the functions in the Ecto module.

**Comment by pma** [comment]
@developerworks This was updated only in the branch https://github.com/pma/riak_ecto/tree/one_bucket_type_per_model.

This branch maps each model to a bucket-type, and buckets are used as query prefixes to enable for example data segregation by user/account. The reasoning is that according to the Riak docs, configuring Solr indexes at the bucket level has a higher cost that at the bucket type level (more config data needs to be exchanged by the gossip protocol).

Another advantage is that it allows choosing a backend per model, since the backend is configured at the bucket type level.
